#!/usr/bin/env python3

def get_reverse_complement(dna):
	dna_Gc = dna.replace('G','c')
	dna_Cg_Gc = dna_Gc.replace('C','g')
	dna_At_Cg_Gc = dna_Cg_Gc.replace('A','t')
	dna_Ta_At_Cg_Gc = dna_At_Cg_Gc.replace('T','a')
	DNA_complement = dna_Ta_At_Cg_Gc.upper()
	DNA_reverse_complement = DNA_complement[::-1]	
	return DNA_reverse_complement


dna = 'GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCT'

print(get_reverse_complement(dna))
